zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      serviceId: HELLO-SERVER
    hello-client:
      path: /client/**
      serviceId: HELLO-CLIENT
    employee-producer:
      path: /producer/**
      serviceId: EMPLOYEE-PRODUCER
    employee-consumer:
      path: /consumer/**
      serviceId: EMPLOYEE-CONSUMER
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    instance:
      hostname: localhost
      
server:
  port: 8079
  
spring:
  application:
    name: zuul-service

#Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000